In [2]:
import pandas as pd
import plotly.express as px
import seaborn as sns
import sklearn.cluster as cluster
from sklearn.cluster import KMeans
from scipy.spatial import distance as sdist

df = pd.read_csv('personality.csv')
df.head()

,Agreeableness,Extraversion,Intellect,Neuroticism,Conscientiousness,Individualism vs Collectivism,Masculinity vs Femininity,Power Distance,Indulgence vs Restraint,Long term orientation,Uncertainty avoidance
0,4.2,4.0,4.2,2.8,4.6,3.50,3.50,3.50,3.00,4.00,3.00
1,3.6,4.0,3.6,4.6,3.8,3.25,3.00,3.75,2.75,3.25,3.00
2,4.4,4.0,4.2,4.2,4.2,3.75,3.25,3.25,3.50,3.25,2.75
3,4.2,4.0,4.4,3.6,4.8,3.25,3.75,3.25,3.75,4.50,3.00
4,4.6,2.0,3.8,3.4,3.8,3.75,2.75,2.75,3.00,3.50,2.75